AllBetsProject/urls.py
"""
Definition of urls for AllBetsProject.
"""

from datetime import datetime
from django.urls import re_path, path, include
from django.contrib import admin
from allauth.account.views import LoginView, LogoutView
from app import forms, views


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    #path('login/',
    #     LoginView.as_view
    #     (
    #         template_name='app/login.html',
    #         authentication_form=forms.BootstrapAuthenticationForm,
    #         extra_context=
    #         {
    #             'title': 'Log in',
    #             'year' : datetime.now().year,
    #         }
    #     ),
    #     name='login'),
    #path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls, name='admin'),
    #ACCOUNTS
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/my_bank/', views.MyBankView.as_view(), name='my_bank'),
    path('accounts/login/', views.MyLoginView.as_view(), name='login'),
    re_path(r'^accounts/', include('allauth.urls')),
    #BETS
    path('bets/all/', views.BetListView.as_view(), name='all_bets'),
    path('bets/<int:pk>/details/', views.BetDetailView.as_view(), name='bet_detail'),
    path('bets/new/', views.BetCreationView.as_view(), name='bet_creation'),
    path('bets/<int:pk>/create_betting/', views.CreateBet.as_view(), name='betting_creation'),
    path('bets/my_bets/', views.MyBetsView.as_view(), name='my_bets'),
    path('bets/<int:pk>/admin/', views.BetAdminView.as_view(), name='admin_bet'),
]

app/models.py
"""
Definition of models.
"""

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.dispatch import receiver
from allauth.account.signals import email_confirmed, user_signed_up
from django.urls import reverse
from decimal import *


class BankAccount(models.Model):
    balance = models.DecimalField(max_digits=20, decimal_places=2)
    authorized_overdraft = models.DecimalField(max_digits=20, decimal_places=2)
    date_open = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField()
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def __str__(self):
        return self.user.username + '\'s account'


class BankOperation(models.Model):
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=264)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    account = models.ForeignKey(BankAccount, on_delete=models.SET_NULL, null=True)


class Bet(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    expiration_date = models.DateTimeField()
    creator = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=User.objects.get(username="AllBets").pk)
    extendable = models.BooleanField()
    title = models.CharField(max_length=264)
    summary = models.TextField()

    def get_entries_count(self): 
        return Betting.objects.filter(option__bet=self).count()

    def get_total_invested(self):
        sum = Betting.objects.filter(option__bet=self).aggregate(Sum('amount'))['amount__sum']
        return float(sum) if sum is not None else 0

    def __str__(self):
        return self.title + " by " + self.creator.username

    def get_absolute_url(self):
        return reverse('bet_detail', args=[self.id])


class BetOption(models.Model):

    creation_date = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=User.objects.get(username="AllBets").pk)
    title = models.CharField(max_length=264)
    rating = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    bet = models.ForeignKey(Bet, on_delete=models.CASCADE)

    def get_entries_count(self): 
        return Betting.objects.filter(option=self).count()

    def get_total_invested(self):
        sum = Betting.objects.filter(option=self).aggregate(Sum('amount'))['amount__sum']
        return float(sum) if sum is not None else 0

    def get_current_rating(self):
        self_total = self.get_total_invested()
        if self_total > 0:
            rate = self.bet.get_total_invested()*0.85/self.get_total_invested()
            return round(rate, 2)
        else: return 0

    def __str__(self):
        return self.bet.title + " : " + self.title


class Betting(models.Model):

    date = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    option = models.ForeignKey(BetOption, on_delete=models.CASCADE)

    def get_current_payback(self):
        payback = self.amount*Decimal(self.option.get_current_rating())
        return round(payback, 2)

    def __str__(self):
        return self.creator.username + "'s betting " + str(self.amount) + " on option " + str(self.option)

app/templates/bets/bet_creation.html
{% extends "app/layout.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Create Bet" %}{% endblock %}

{% block content %}

{% crispy form %}

{% block admin_panel %}
{% endblock %}

{% endblock %}

app/templates/bets/bet_detail.html
{% extends "app/layout.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load staticfiles %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

<h1>{{ bet.title }}</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">{% trans "Entries" %}</th>
            <th scope="col">{% trans "Total invested" %}</th>
            <th scope="col">{% trans "Current rating" %}</th>
            <th scope="col">{% trans "Creator" %}</th>
            <th scope="col">{% trans "Created on" %}</th>
            {% if user.is_authenticated %}
            <th scope="col">{% trans "I'm betting !" %}</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for option in bet.betoption_set.all %}
        
        <tr> 
            <td class="option-title">{{ option.title }} </td>
            <td class="option-entries-count">{{ option.get_entries_count }} </td>
            <td class="option-total-invested">{{ option.get_total_invested }} </td>
            <td class="option-current-rating">{{ option.get_current_rating }} </td>
            <td class="option-creator">{{ option.creator }} </td>
            <td class="option-creation-date">{{ option.creation_date }} </td>
            {% if user.is_authenticated %}
            <td class="betting-col"><form action="{% url 'betting_creation' bet.id %}" method="post">{% csrf_token %}
                <input type="number" name="amount" min="0" max="{{ user.bankaccount.balance }}" step="0.01" class="amount-input"/>
                <input type="hidden" name="betoption" value="{{ option.id }}"/>
                <button type="button" class="see-gains">{% trans "See potential gain" %}</button>
                <br />
                <span class="virtual-gain-wrapper" style="visibility:hidden">{% trans "Your potential gain" %} : <span class="virtual-gain"></span></span>
                <button type="submit" class="submit-bet" style="visibility:hidden">{% trans "Bet" %}</button>
            </form>
            </td>
            {% endif %}
        </tr>
        
        {% endfor %}
    </tbody>
</table>

{% endblock %}


{% block scripts %}
<script src="{% static 'app/scripts/jquery-1.10.2.min.js' %}"></script>
<script type="text/javascript">
     $('.see-gains').on('click', function (e) {
        var input = $(this).siblings('.amount-input');
        var amount = Number(input.val());
        var a = ({{ bet.get_total_invested }}+amount)*0.85;
        var b = Number(input.closest('tr').find('.option-total-invested').text())+amount;
        var rate = a/b;
        var gain = amount*rate;

        input.closest('.betting-col').find('.virtual-gain').html(gain.toFixed(2));
        input.siblings('.submit-bet').css("visibility", "visible");
        input.siblings('.virtual-gain-wrapper').css("visibility", "visible");
    });
</script>
{% endblock %}

app/templates/bets/bet_list.html
{% extends "app/layout.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

<h1>{% trans "List of all bets" %}</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">{% trans "Entries" %}</th>
            <th scope="col">{% trans "Total invested" %}</th>
            <th scope="col">{% trans "Creator" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for bet in bet_list %}
        <tr> 
            <td><a href="{% url 'bet_detail' bet.id %}">{{ bet.title }} </a></td>
            <td>{{ bet.get_entries_count }} </td>
            <td>{{ bet.get_total_invested }} </td>
            <td>{{ bet.creator }} </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div><a href="{% url 'bet_creation' %}">+ Create new bet</a></div>

{% endblock %}

app/templates/bets/bet_update.html
{% extends "bets/bet_creation.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load staticfiles %}

{% block admin_panel %}
<button type="button" id="close-bet-btn">Close Bet</button>
{% endblock %}

app/templates/bets/betoptions_formset.html
{% load crispy_forms_tags %}
{% load staticfiles %}
<table>
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
            <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
                {% endfor %}
            </tr>
    {% endfor %}

</table>
<br>
<script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
<script src="{% static 'app/scripts/bootstrap.js' %}"></script>
<script src="{% static 'app/scripts/respond.js' %}"></script>
<script src="{% static 'app/scripts/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

app/templates/bets/my_bets.html
{% extends "app/layout.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load staticfiles %}

{% block head_title %}{% trans "My Bets" %}{% endblock %}

{% block content %}

<h1>{% trans "Bets I created" %}</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">{% trans "Entries" %}</th>
            <th scope="col">{% trans "Total invested" %}</th>
            <th scope="col">{% trans "Creator" %}</th>
            <th scope="col">{% trans "Expire on" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for bet in active_bets %}
        <tr> 
            <td><a href="{% url 'admin_bet' bet.id %}">{{ bet.title }} </a></td>
            <td>{{ bet.get_entries_count }} </td>
            <td>{{ bet.get_total_invested }} </td>
            <td>{{ bet.creator }} </td>
            <td>{{ bet.expiration_date }} </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div><a href="{% url 'bet_creation' %}">+ Create new bet</a></div>

<h1>{% trans "Current bettings" %}</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">{% trans "Answer" %}</th>
            <th scope="col">{% trans "Invested" %}</th>
            <th scope="col">{% trans "Current expected payback" %}</th>
            <th scope="col">{% trans "Expire on" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for betting in active_bettings %}
        <tr> 
            <td><a href="{% url 'bet_detail' betting.option.bet.id %}">{{ betting.option.bet.title }} </a></td>
            <td>{{ betting.title }} </td>
            <td>{{ betting.amount }} </td>
            <td>{{ betting.get_current_payback }} </td>
            <td>{{ betting.option.bet.expiration_date }} </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}